name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bazelversion:
          - 8.2.0
        folder:
          - .
          # - e2e
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
          bazelrc: |
            import %workspace%/.github/workflows/ci.bazelrc
      - name: bazel test //...
        working-directory: ${{ matrix.folder }}
        env:
          USE_BAZEL_VERSION: ${{ matrix.bazelversion }}
        run: bazel test //...
